### PR TITLE
Adds optional tab bar drag when meta key pressed.

### LINKED ISSUE #13: Optional drag window using keyboard modifier
Based on @eboracus's [suggestion](https://github.com/atom/atom/pull/13616#issuecomment-285707712). Provide an option to enable window dragging from the tab bar whenever a user holds down chosen modifier key on the keyboard.

### PR DESCRIPTION
**Pull request by lexicalunit**
Resolves #13.

### CODE REVIEW

**Comment by lexicalunit** [comment]
This PR doesn't _quite_ implement your suggestion in as seamless a way as I would like, @eboracus. But it's pretty close!

The only thing I can't figure out so far is when a user moves over the tab bar, then presses `cmd`, and then starts dragging. I am not capturing the key press event, so we need at least one mouse event with the `cmd` key pressed down in order to trigger the no-drag toggle. I know I can capture the key press event itself, but it seems really invasive to add an event listener for key press to Atom.

This PR **does** work if the user is already holding `cmd` as they enter the tab bar, or jiggles the mouse a little after beginning to hold down `cmd` after entering the tab bar.

**Comment by eboracus** [comment]
Nice! 👍 

So the mouse click to start dragging doesn't itself count as the required event to trigger? :( Never actually tried anything with listening for mouse events so not sure what the optimum approach would be, but would it be possible (if requirements of cursor in the tab bar & `cmd` key is pressed are met - in the `handleEvents()` function) to artificially create a 'faked' mouse event automatically? Or maybe after a very short delay of `cmd` being held down(?) - not sure if this would work 'smoothly' in practice.

**Comment by lexicalunit** [comment]
I tried using the mousedown event as well, but the problem with that is that the drag/no-drag status when the mouse was pressed it what gets used, even if you change the setting when you handle the event. :(

**Comment by lexicalunit** [comment]
So I added some visual feedback as @j-f1 suggested and put the feature behind a configuration toggle. I think it's good enough to be released now, especially with the config toggle defaulted to off. Perhaps someone else can try improving it, or maybe it's good enough already as it is.

**Pull request merged**
